#
# (C) Copyright Black Sesame Technologies (Shanghai)Ltd. Co., 2020. All rights reserved.
#
# This file contains proprietary information that is the sole intellectual property of Black
# Sesame Technologies (Shanghai)Ltd. Co. No part of this material or its documentation 
# may be reproduced, distributed, transmitted, displayed or published in any manner 
# without the written permission of Black Sesame Technologies (Shanghai)Ltd. Co.

obj-$(CONFIG_DDR_TEST) += ddr/ 
obj-$(CONFIG_IPC_TEST) += ipc/
obj-$(CONFIG_A55_TIMER_TEST) += a55_timer/
obj-$(CONFIG_GDMA_TEST) += gdma/
obj-$(CONFIG_I2C_TEST) += i2c/
obj-$(CONFIG_UART_TEST) += uart/
obj-$(CONFIG_GPIO_TEST) += gpio/
obj-$(CONFIG_WDT_TEST) += wdt/
obj-$(CONFIG_PWM_TEST) += pwm/
obj-$(CONFIG_NOC_TEST) += noc/
obj-$(CONFIG_A55_INT_TEST) += a55_int/
obj-$(CONFIG_LSP_PARITY_TEST) += lsp_parity/
obj-$(CONFIG_QSPI_TEST) += qspi/
obj-$(CONFIG_EVB) += clock/
obj-$(CONFIG_COREIP_ISP_TEST) += isp/
obj-$(CONFIG_COREIP_VSP_TEST) += vsp/
obj-$(CONFIG_SOC_PERF_TEST) += soc_perf/
