xtor-y += $(xtor_dir)/i2c/I2cSlave.o $(xtor_dir)/i2c/I2cMaster.o

xtor-$(CONFIG_I2C_SLAVE_GENERAL) += $(xtor_dir)/i2c/I2cSlaveGeneral.o
xtor-$(CONFIG_I2C_MASTER_GENERAL) += $(xtor_dir)/i2c/I2cMasterGeneral.o

