#
# (C) Copyright Black Sesame Technologies (Shanghai)Ltd. Co., 2020. All rights reserved.
#
# This file contains proprietary information that is the sole intellectual property of Black
# Sesame Technologies (Shanghai)Ltd. Co. No part of this material or its documentation 
# may be reproduced, distributed, transmitted, displayed or published in any manner 
# without the written permission of Black Sesame Technologies (Shanghai)Ltd. Co.

obj-y := help.o
obj-y += version.o
obj-$(CONFIG_CMD_OLD_CLI) += old_cli.o
obj-$(CONFIG_CMD_GET_IPID) += get_ipid.o
obj-$(CONFIG_CMD_GPIO) += cmd_gpio.o
obj-$(CONFIG_CMD_UART) += cmd_uart.o
obj-$(CONFIG_CMD_I2C) += i2c.o
obj-$(CONFIG_CMD_ISP) += isp.o
obj-$(CONFIG_CMD_VSP) += vsp.o
obj-$(CONFIG_CMD_MEMORY) += mem.o
obj-$(CONFIG_CMD_DMAC) += dmac.o
obj-$(CONFIG_CMD_SOC_PERF) += soc_perf.o
