xtor-$(CONFIG_UART0_INIT) += $(xtor_dir)/uart/Uart0.o
xtor-$(CONFIG_UART1_INIT) += $(xtor_dir)/uart/Uart1.o
xtor-$(CONFIG_UART3_SYNC) += $(xtor_dir)/uart/Uart_Sync.o
xtor-y += $(xtor_dir)/uart/Uart3.o
xtor-y += $(xtor_dir)/uart/UartCommon.o

