include $(tb_dir)/$(xtor_dir)/common/Makefile

ifeq ($(CONFIG_XTOR_UART),y)
include $(tb_dir)/$(xtor_dir)/uart/Makefile
endif

ifeq ($(CONFIG_XTOR_I2C),y)
include $(tb_dir)/$(xtor_dir)/i2c/Makefile
endif

